services:
  - type: web
    name: onmuymind-bot
    env: go
    plan: starter # Adjust based on your needs
    buildCommand: ./render-build.sh
    startCommand: ./mindbot
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENROUTER_KEY
        sync: false
      - key: DATA_DIR
        value: /data
      - key: PORT
        value: "8080"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 